- name: playing with loops
  hosts: local
  connection: local
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - nginx
      - apache
      - mysql