- name: playing with functions
  hosts: local
  connection: local
  become: true
  vars:
    Server: windows,linux,mac
    name: "My name is reddy"
    gmail: "SASigk;mxnn@"
    ipadd: 172.169.9.0
    # dict to map
    tags:
      application: phonepay
      pay: amount
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "print default: {{name | default('reddy')}}"
  - name: print the list of servers
    ansible.builtin.debug:
      msg: "print list: {{ Server | split(',') }}"
  - name: print the dict value
    ansible.builtin.debug:
      msg: "print dict: {{ tags | dict2items }}"
  - name: convert to upper
    ansible.builtin.debug:
      msg: "print upper: {{ name | upper }}"
  - name: convert to lower
    ansible.builtin.debug:
      msg: "print lower: {{ gmail | lower }}"
  - name: to find valid ip address
    ansible.builtin.debug: "{{ipadd | ansible.utils.ipv4}}"
  