- name: playing with functions
  hosts: local
  connection: local
  become: true
  vars:
    Server: windows,linux,mac
    name: "My name is reddy"
    gmail: "SASigk;mxnn@"
    ipadd: 1724.31.18.203
    # dict to map
    tags:
      application: phonepay
      pay: amount
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "print default: {{name | default('reddy')}}"
  - name: print the list of servers
    ansible.builtin.debug:
      msg: "print list: {{ Server | split(',') }}"
  - name: print the dict value
    ansible.builtin.debug:
      msg: "print dict: {{ tags | dict2items }}"
  - name: convert to upper
    ansible.builtin.debug:
      msg: "print upper: {{ name | upper }}"
  - name: convert to lower
    ansible.builtin.debug:
      msg: "print lower: {{ gmail | lower }}"
  - name: to find valid ip address
    ansible.builtin.debug: 
      msg: "print valid ip: {{ipadd | ansible.utils.ipv4}}"
  - name: find root pwd
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: rootpwd
  - name: print the root pwd
    ansible.builtin.debug:
      msg: "print root pwd: {{ rootpwd.stdout }}"
  - name: Do pathn redirection usig command
    ansible.builtin.command: ls -lrt  /tmp/passwd.txt
    register: pathredirect
  - name: print the path redirection
    ansible.builtin.debug:
      msg: "print path redirection: {{ pathredirect }}"
    ignore_errors: true

  - name: Do pathn redirection usig shell
    ansible.builtin.shell: ls -lrt  /tmp/passwd.txt
    register: pathredirect

  - name: print the path redirection
    ansible.builtin.debug:
      msg: "print path redirection: {{ pathredirect }}"

  